[profile.dev]
split-debuginfo = "unpacked"

[workspace]
members = [
  "account-compression/programs/account-compression",
  "account-compression/programs/noop",
  "libraries/concurrent-merkle-tree",
  "libraries/merkle-tree-reference",
]

exclude = [
]

resolver = "2"
