name: Account Compression Pull Request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format_and_lint_client_js:
    name: Format & Lint Client JS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: account-compression
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Format Client JS
        run: pnpm clients:js:format

      - name: Lint Client JS
        run: pnpm clients:js:lint

  generate_clients:
    name: Check Client Generation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: account-compression
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Generate Clients
        run: pnpm generate:clients

      - name: Check Working Directory
        run: |
          git status --porcelain
          test -z "$(git status --porcelain)"

  js-test-account-compression:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: pnpm/action-setup@v4
      - uses: actions/cache@v4
        with:
          path: ~/.npm
          key: node-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            node-
      - run: ./ci/js-test-account-compression.sh
      - uses: actions/upload-artifact@v3
        with:
          name: account-compression-programs
          path: |
            target/deploy/spl_account_compression.so
            target/deploy/spl_noop.so
          if-no-files-found: error
